# Generated by Django 4.0.2 on 2022-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playlist_video_delete_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='url_playlist_yt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_video_yt',
            field=models.CharField(max_length=255),
        ),
    ]
