# Generated by Django 4.0.2 on 2022-03-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_playlist_url_playlist_yt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='url_playlist_yt',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_video_yt',
            field=models.URLField(),
        ),
    ]
