# Generated by Django 4.0.2 on 2022-03-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_playlist_url_playlist_yt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.playlist'),
            preserve_default=False,
        ),
    ]
