# Generated by Django 4.0.2 on 2022-03-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_playlist_title_video_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
